In [1]:
import tensorflow as tf

from modules.training.cme_modeling import ModelBuilder as MB

C:\Users\the_3\anaconda3\envs\tf-gpu\lib\site-packages\tensorflow_addons\utils\tfa_eol_msg.py:23: UserWarning: 

TensorFlow Addons (TFA) has ended development and introduction of new features.
TFA has entered a minimal maintenance and release mode until a planned end of life in May 2024.
Please modify downstream libraries to take dependencies from other repositories in our TensorFlow community (e.g. Keras, Keras-CV, and Keras-NLP). 

For more information see: https://github.com/tensorflow/addons/issues/2807 

  warnings.warn(
C:\Users\the_3\anaconda3\envs\tf-gpu\lib\site-packages\tensorflow_addons\utils\ensure_tf_install.py:53: UserWarning: Tensorflow Addons supports using Python ops for all Tensorflow versions above or equal to 2.12.0 and strictly below 2.15.0 (nightly versions are not supported). 
 The versions of TensorFlow you are currently using is 2.10.1 and is not supported. 
Some things might work, some things might not.
If you were to encounter a bug, do not file an issue.
If 

In [2]:
from modules.training.phase_manager import TrainingPhaseManager

# instantiate the model_builder
mb = MB()
pm = TrainingPhaseManager()  # Training phase manager

In [3]:
# y_true = tf.constant([[-1.0],
#                       [ 3],
#                       [ 1.0]])
# 
# z_pred = tf.constant([[-1.0,  1.0],
#                       [ 0.5,  0.0],
#                       [ 1.0, -1.0],
#                       ])

y_true = tf.constant([[1.0],
                      [2.0],
                      [3.0]])

z_pred = tf.constant([[1.0, 1.0],
                      [2.0, 2.0],
                      [3.0, 3.0],
                      ])


In [4]:
loss = mb.pdc_loss_vec(y_true, z_pred, pm)
print(f"PDC Loss: {loss.numpy()}")

Dy_mean: 2.0, Dz_mean: 4.0
Dy_centered: [[-2. -1.  2.]
 [-1. -2. -1.]
 [ 2. -1. -2.]], Dz_centered: [[-4. -2.  4.]
 [-2. -4. -2.]
 [ 4. -2. -4.]]
tf.Tensor(
[[0. 1. 1.]
 [1. 0. 1.]
 [1. 1. 0.]], shape=(3, 3), dtype=float32)
cov_Dy_Dz: 24.0, var_Dy: 12.0, var_Dz: 48.0
pcc: 1.0
PDC Loss: 0.0


In [5]:
loss = mb.pdc_loss_vec_old(y_true, z_pred, pm)
print(f"PDC Loss: {loss.numpy()}")

mean_Dy: 2.0, mean_Dz: 4.0
Dy_centered: [-1.  2. -1.], Dz_centered: [-2.  4. -2.]
cov_Dy_Dz: 12.0, var_Dy: 6.0, var_Dz: 24.0
pcc: 1.0
PDC Loss: 0.0


In [6]:
import numpy as np

# Parameters
num_points = 200  # 201 points for labels from -100 to 100 inclusive

# Create evenly spaced labels from -100 to 100
labels = np.linspace(-100, 100, num_points)
# update the dimension of labels
labels = np.expand_dims(labels, axis=1)

# Generate points like (0, 0), (1, 1), ..., (200, 200)
points = np.array([(i, i) for i in range(num_points)])

# convert to tensor float32
labels = tf.constant(labels, dtype=tf.float32)
points = tf.constant(points, dtype=tf.float32)

# Random sample weights between 0 and 1
sample_weights = np.random.rand(num_points)

In [7]:
# # print the labels and points 
# print(f"Labels: {labels}")
# print(f"Points: {points}")

In [8]:
loss = mb.pdc_loss_vec(labels, points, pm)
print(f"PDC Loss: {loss.numpy()}")

Dy_mean: 6767.50634765625, Dz_mean: 13400.0
Dy_centered: [[-6767.5063 -6766.496  -6763.466  ... 32432.518  32831.49   33232.492 ]
 [-6766.496  -6767.5063 -6766.496  ... 32035.553  32432.514  32831.49  ]
 [-6763.466  -6766.496  -6767.5063 ... 31640.615  32035.553  32432.518 ]
 ...
 [32432.518  32035.553  31640.615  ... -6767.5063 -6766.496  -6763.466 ]
 [32831.49   32432.514  32035.553  ... -6766.496  -6767.5063 -6766.496 ]
 [33232.492  32831.49   32432.518  ... -6763.466  -6766.496  -6767.5063]], Dz_centered: [[-13400. -13398. -13392. ...  64218.  65008.  65802.]
 [-13398. -13400. -13398. ...  63432.  64218.  65008.]
 [-13392. -13398. -13400. ...  62650.  63432.  64218.]
 ...
 [ 64218.  63432.  62650. ... -13400. -13398. -13392.]
 [ 65008.  64218.  63432. ... -13398. -13400. -13398.]
 [ 65802.  65008.  64218. ... -13392. -13398. -13400.]]
tf.Tensor(
[[0. 1. 1. ... 1. 1. 1.]
 [1. 0. 1. ... 1. 1. 1.]
 [1. 1. 0. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 0. 1. 1.]
 [1. 1. 1. ... 1. 0. 1.]
 [1. 1. 

In [9]:
loss = mb.pdc_loss_vec_old(labels, points, pm)
print(f"PDC Loss: {loss.numpy()}")

mean_Dy: 6767.50634765625, mean_Dz: 13400.0
Dy_centered: [-6766.496  -6763.466  -6758.4155 ... -6766.496  -6763.466  -6766.496 ], Dz_centered: [-13398. -13392. -13382. ... -13398. -13392. -13398.]
cov_Dy_Dz: 2504762851328.0, var_Dy: 1264999989248.0, var_Dz: 4959555813376.0
pcc: 0.9999998807907104
PDC Loss: 1.1920928955078125e-07
